;
-- CREATE TABLE CUSTOMER (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   cif_number BIGINT,
--   first_name varchar(255),
--   last_name varchar(255),
--   created_at TIMESTAMP,
--   updated_at TIMESTAMP
-- );
--
-- CREATE TABLE ACCOUNT (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   account_number varchar(255),
--   customer_id BIGINT,
--   balance BIGINT,
--   created_at TIMESTAMP,
--   updated_at TIMESTAMP
-- );